In [9]:
#openCV
import cv2
from pop import Util

Util.enable_imshow()
Util.createIMG()

In [10]:
#image 크기
image = cv2.imread("img.jpg", cv2.IMREAD_COLOR)
#h, w, c
h, w, c = image.shape
print("width : %d, height : %d, channel : %d" % (w, h, c))

width : 640, height : 480, channel : 3


In [11]:
#color / gray 출력
from pop.Util import imshow
imshow("color", image)
image_gray = cv2.imread("img.jpg", cv2.IMREAD_GRAYSCALE)
imshow("gray", image_gray)

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [17]:
#cam 크기 설정
cam = Util.gstrmer(width = 640, height = 480)

In [18]:
#camera 
camera = cv2.VideoCapture(cam, cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("Not found camera")
width = camera.get(cv2.CAP_PROP_FRAME_WIDTH)
height = camera.get(cv2.CAP_PROP_FRAME_HEIGHT)
print("init width %d, init hegiht %d" % (width, height))


init width 640, init hegiht 480


In [16]:
for _ in range(120):
    ret, frame = camera.read()
    if not ret:
        print("no")
        break
    cv2.imshow("soda", frame)

camera.release()
cv2.destroyAllWindows()

no


In [21]:
#배열 numpy
import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [28]:
#array -> list
arr = np.array([-2, 0, 2, 4, 6, 8, 10])
print(arr.tolist())

[-2, 0, 2, 4, 6, 8, 10]


In [64]:
#10개 데이터 저장배열 0으로 초기화
#cds값 10개 배열에 저장
#배열 2행5열 배열로 바꿔라
from pop import Cds as cds
from ipywidgets import widgets
import time
lab=[]
Cds = cds
arr = np.zeros(10, dtype = int)
arr2 = np.resize(arr,(5,2))
print(arr2)
print(arr.tolist())
print(arr)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0 0 0 0 0 0 0 0 0 0]


In [91]:
from pop import Cds as cds
import time

Cds = cds
cds=Cds(7)

arr = np.zeros(10, dtype = int)
count = 0
while count < 10:
    arr[count] = cds.read()
    time.sleep(0.1)
    print("count : ", count, end = ", ")
    print("Cds : ", arr[count])
    count = count + 1
print("arr : ", arr)
reshape_arr = np.reshape(arr,(2,5))
print("reshape_arr : ")
print(reshape_arr)

count :  0, Cds :  1946
count :  1, Cds :  1954
count :  2, Cds :  1965
count :  3, Cds :  1975
count :  4, Cds :  1984
count :  5, Cds :  1990
count :  6, Cds :  1988
count :  7, Cds :  1970
count :  8, Cds :  1927
count :  9, Cds :  1869
arr :  [1946 1954 1965 1975 1984 1990 1988 1970 1927 1869]
reshape_arr : 
[[1946 1954 1965 1975 1984]
 [1990 1988 1970 1927 1869]]
